### ISSUE TITLE
Making 'RETURNING *||columns' agument optional

### ISSUE THREAD

**Issue by Heberth** [pgjdbc/r2dbc-postgresql#386]
Feel free to close this because I am attempting to use this driver to connect to a Redshift database.

I could be mistaken, but it seems like every insert execution is calling GeneratedValuesUtils.augment which concatenates `RETURNING *` or `RETURNING [column_names]` to the sql insert statement. I understand this is supported by postgres, which Redshift forks from. 

I'm working on a simple connector that's writing to Redshift, but haven't had any luck finding a reactive driver for it. This one works for most cases, but I'm getting `ErrorResponse{fields=[Field{type=SEVERITY_LOCALIZED, value='ERROR'}, Field{type=CODE, value='42601'}, Field{type=MESSAGE, value='syntax error at or near "RETURNING"'}` when inserting. 

I know this would probably require extra logic to actually get the inserted row.

Thank you for your time!

**Comment by mp911de** [comment]
Appending `RETURNING` is a consequence of calling `Statement.returnGeneratedValues(…)`. This driver mirrors what the JDBC driver is doing so that issue should also happen when using the JDBC driver.

I think you could mitigate the problem by either not calling `returnGeneratedValues(…)` from your application or by wrapping the `Connection`/`Statement` objects from this driver and suppressing calls to `returnGeneratedValues(…)`.
