### ISSUE TITLE
Add enum array support

### ISSUE THREAD

**Issue by mmenard-hmrc** [pgjdbc/r2dbc-postgresql#391]
#### Versions

- Driver: 0.8.7.RELEASE

#### Current Behavior

According to the documentation, Postgres Enum Types are covered, by using EnumCodec.
Also, arrays are supported, like text[] type for example.

But I tried to have an array of enum in my model, and I am getting this error if I map to EnumSet<MyEnum> :

```java
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object with OID 16834
```

#### Table schema

<details>
<summary>Input Code</summary>

```sql
my_enum_field my_enum_type[] NOT NULL;
```

</details>

#### Steps to reproduce

<details>

in model class:

```java
private EnumSet<MyEnumType> myEnumField; // same with List<MyEnumType>
```
</details>

**Comment by mp911de** [comment]
Array support is limited to a few basic data types right now. We'd need to revisit the current arrangement to ensure we can scale out for supporting all types as arrays. Right now, each array type requires a bit of a dance to be supported.

In general, we don't support collection types in R2DBC because we cannot obtain its component type during runtime.
