### ISSUE TITLE
Driver doesn't insert anything without additional `getRowsUpdated` call

### ISSUE THREAD

**Issue by dstepanov** [pgjdbc/r2dbc-postgresql#427]
Happens in the latest 0.8.8.RELEASE

Please see the following test in the Micronaut Data that reproduces it:

https://github.com/micronaut-projects/micronaut-data/blob/ddf11c1e8a7a27a1f6765cc5e1c1c3d3f74b475f/data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/PlainR2dbcSpec.groovy#L136-L155

**Comment by mp911de** [comment]
This is expected behavior. You need to consume the result (`Result.getRowsUpdated()`, `Result.map(…)`) to ensure full query execution. 

`Statement.execute()` returns `Publisher<Result>` and due to the streaming nature, you need to consume all `Results` to ensure full query execution. Each `Result` can generate `0..N` rows and with TCP backpressure in mind, drivers linearize their operations in the sense that upon result consumption the first query gets run, then you consume the result before you can issue a second query and consume the next result.

Helping to think what should happen with the next result when you stop consuming rows of the first result is helpful to understand where this concept comes from.

**Comment by dstepanov** [comment]
Thanks, in a way it makes sense but in practice when you call `execute` subscribe and get something that is called `Result` doesn't mean that the statement is actually is executed is very confusing. I thought that there is some benefit of not calling `getRowsUpdated` when I don't need it.

**Comment by mp911de** [comment]
Without knowing what/how you want to consume the result, we cannot drain frames from the transport buffers. `Result` internally represents a `Publisher<…>` that emits some kind of result (in R2DBC SPI 0.9 `Publisher<Segment>`). 

Calling `getRowsUpdated()` skips row frame processing and therefore it's already optimized. Do you have a suggestion of how we could improve the specification?

**Comment by dstepanov** [comment]
Probably the naming got me confused.
I was thinking that if there was a method in the style of `map` you would be able to detect internally that somebody requested a particular result and do the default execution otherwise.

**Comment by mp911de** [comment]
To give you a bit more insight. The Postgres protocol (and a few others) consists of sending a query to the server and then you get in response column descriptors, row data and a command completed/error frame. `getRowsUpdated()` only consumes command completion that holds the affected rows count and error frames while `map(…)` processes column descriptors and row data.

Is there anything else we can do here in the context of this ticket?

**Comment by dstepanov** [comment]
No thanks, I think we can close it.
